import { FileText, TrendingUp, RefreshCw } from 'lucide-react';

export function WhenReady() {
  return (
    <div className="space-y-8 pb-16">
      <div>
        <p style={{ color: '#DC4C0C', fontWeight: 800, letterSpacing: '0.06em', fontSize: '14px', marginBottom: '30px' }}>09</p>
        <h1 style={{ fontFamily: '"Iowan Old Style", "Palatino Linotype", "Book Antiqua", Georgia, serif', fontWeight: 600, letterSpacing: '-0.03em', fontSize: 'clamp(2.2rem, 3.8vw, 3.2rem)', color: '#0F0F0F', marginBottom: '30px' }}>
          When You're Ready
        </h1>
        <div style={{ width: '40px', height: '3px', backgroundColor: '#DC4C0C', marginTop: '30px', marginBottom: '16px' }} />
      </div>

      <div className="bg-white rounded-xl p-8 border border-[#E5E3DD]">
        <p className="text-[#1A1614] leading-relaxed mb-6">
          This reading is the foundation. It shows what is — your psychological architecture as it sits in this season. If you want to see how this architecture shows up in specific contexts — leadership, parenting, relationships, wellbeing — secondary reports apply this same reading through those lenses. If you want to actually build, the development product teaches the practice of strengthening psychological foundations. And if you are holding this reading on your own, it is specific enough to bring to a therapist or coach who knows you.
        </p>

        <p className="text-[#1A1614] leading-relaxed">
          This reading captures a season. Retesting after intentional work, or after a meaningful life shift, is its own practice.
        </p>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <NextStepCard
          icon={<FileText className="w-6 h-6" />}
          title="Explore secondary reports"
          description="See how your architecture shows up in leadership, relationships, and specific life contexts"
          color="#42A68E"
        />

        <NextStepCard
          icon={<TrendingUp className="w-6 h-6" />}
          title="Learn about development"
          description="Discover the practice of strengthening psychological foundations with guided work"
          color="#DC4C0C"
        />

        <NextStepCard
          icon={<RefreshCw className="w-6 h-6" />}
          title="Schedule a retest"
          description="Retake the assessment after intentional work or a meaningful life shift"
          color="#FFAB00"
        />
      </div>

      <div className="bg-[#F8F6F3] rounded-xl p-8 border border-[#E5E3DD] text-center">
        <p className="text-sm text-[#8B8682]">
          This reading was generated by the Dimensional System on June 9, 2026
        </p>
      </div>
    </div>
  );
}

interface NextStepCardProps {
  icon: React.ReactNode;
  title: string;
  description: string;
  color: string;
}

function NextStepCard({ icon, title, description, color }: NextStepCardProps) {
  return (
    <button className="bg-white rounded-xl p-6 border border-[#E5E3DD] hover:border-[#1A1614] transition-all text-left group">
      <div
        className="w-12 h-12 rounded-lg flex items-center justify-center mb-4 transition-transform group-hover:scale-110"
        style={{ backgroundColor: `${color}20` }}
      >
        <div style={{ color }}>{icon}</div>
      </div>
      <h3 className="font-medium text-[#1A1614] mb-2">{title}</h3>
      <p className="text-sm text-[#1A1614] leading-relaxed">{description}</p>
    </button>
  );
}
